### ISSUE TITLE
A probable problem in radiotap-parser

### ISSUE THREAD

**Issue by shanicky** [Gregwar/Mitm#1]
hi, there

I'm using your library of radiotap-parser to develop a 802.11 sniffer, but I've found a problem probably exists.

``` c
        if ((((void*)iterator->arg)-((void*)iterator->rtheader)) &
            ((rt_sizes[iterator->arg_index] >> 4) - 1))
            iterator->arg_index +=
                (rt_sizes[iterator->arg_index] >> 4) -
                ((((void*)iterator->arg) -
                ((void*)iterator->rtheader)) &
                ((rt_sizes[iterator->arg_index] >> 4) - 1));
```

I guess the `iterator->arg_index` should be `iterator->arg` because I thought `arg` is the pointer while `arg_index` is not.

**Comment by Gregwar** [comment]
Hello,

The whole osdep directory is actually from the famous aircrack project
https://www.aircrack-ng.org/

It is now quite old and I think their code changed
If you investigate this, I'm interrested in keeping this repository up to date by upgrading the tap part
